import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollView: {
    flex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#1E293B",
    marginVertical: 24,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    margin: 16,
    shadowColor: "#475569",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#334155",
    marginBottom: 16,
  },
  subtitle2: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 8,
  },
  bottomContainer: {
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4F46E5",
    padding: 12,
    borderRadius: 8,
  },
  backButtonText: {
    color: "#FFFFFF",
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "600",
  },
  modelContainer: {
    marginVertical: 6,
    borderRadius: 12,
    overflow: "hidden",
  },
  modelButton: {
    backgroundColor: "#EFF6FF",
    padding: 16,
    borderRadius: 12,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    shadowColor: "#3B82F6",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  downloadedModelButton: {
    backgroundColor: "#EFF6FF",
    borderColor: "#3B82F6",
    borderWidth: 1,
  },
  modelButtonContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modelStatusContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  downloadedIndicator: {
    backgroundColor: "#DBEAFE",
    padding: 4,
    borderRadius: 6,
    marginRight: 8,
  },
  notDownloadedIndicator: {
    backgroundColor: "#F1F5F9",
    padding: 4,
    borderRadius: 6,
    marginRight: 8,
  },
  downloadedIcon: {
    color: "#3B82F6",
    fontSize: 14,
    fontWeight: "bold",
  },
  notDownloadedIcon: {
    color: "#94A3B8",
    fontSize: 14,
    fontWeight: "bold",
  },
  downloadedText: {
    color: "#1E40AF",
  },
  loadModelIndicator: {
    backgroundColor: "#DBEAFE",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 8,
  },
  buttonTextGGUF: {
    color: "#64748B",
    fontSize: 14,
    fontWeight: "500",
  },
  selectedButtonText: {
    color: "#1E40AF",
    fontWeight: "600",
  },
  loadModelText: {
    color: "#2563EB",
    fontSize: 12,
    fontWeight: "500",
  },
  downloadIndicator: {
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 8,
  },
  downloadText: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "500",
  },
  selectedButton: {
    backgroundColor: "#EFF6FF",
    borderColor: "#3B82F6",
    borderWidth: 1,
  },
  buttonText: {
    color: "#64748B",
    fontSize: 14,
    fontWeight: "500",
  },
  contentContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 60,
  },
  assistantTitle: {
    fontSize: 42,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 100,
    textAlign: "center",
    letterSpacing: -0.5,
    paddingHorizontal: 20,
  },
  waveformContainer: {
    width: width * 0.6,
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 120,
  },
  voiceContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    position: "relative",
  },
  micButton: {
    position: "absolute",
    bottom: -100,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 10,
    borderWidth: 1,
    borderColor: "#6366f1",
  },
  micButtonActive: {
    backgroundColor: "#6366f1",
    transform: [{ scale: 1.05 }],
    shadowOpacity: 0.2,
    shadowRadius: 10,
    borderWidth: 0,
  },
  micButtonDisabled: {
    backgroundColor: "#f5f5f5",
    transform: [{ scale: 1 }],
    shadowOpacity: 0.1,
    borderWidth: 1,
    borderColor: "#e5e5e5",
  },
  micInstructions: {
    position: "absolute",
    bottom: -160,
    fontSize: 16,
    color: "#666666",
    textAlign: "center",
    letterSpacing: 0.3,
    width: "100%",
  },
  messagesContainer: {
    flex: 1,
    padding: 16,
    width: "100%",
  },
  messageWrapper: {
    marginBottom: 16,
  },
  messageBubble: {
    padding: 12,
    borderRadius: 12,
    maxWidth: "80%",
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#3B82F6",
  },
  llamaBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  messageText: {
    fontSize: 16,
    color: "#334155",
  },
  userMessageText: {
    color: "#FFFFFF",
  },
  thoughtContainer: {
    marginTop: 8,
    padding: 10,
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#94A3B8",
  },
  thoughtTitle: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  thoughtText: {
    color: "#475569",
    fontSize: 12,
    fontStyle: "italic",
    lineHeight: 16,
  },
  toggleButton: {
    marginTop: 8,
    paddingVertical: 4,
  },
  toggleText: {
    color: "#3B82F6",
    fontSize: 12,
    fontWeight: "500",
  },
  // Welcome Screen Styles
  welcomeCard: {
    alignItems: "center",
    padding: 24,
    margin: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "#2D3436",
    marginTop: 24,
    marginBottom: 12,
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 18,
    color: "#636E72",
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 24,
  },
  welcomeFeatures: {
    width: "100%",
    marginTop: 16,
    marginBottom: 32,
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 12,
    padding: 16,
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
  },
  featureText: {
    fontSize: 16,
    color: "#2D3436",
    marginLeft: 16,
    lineHeight: 22,
  },
  getStartedButton: {
    backgroundColor: "#FF6B6B",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 16,
    shadowColor: "#FF6B6B",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4.65,
    elevation: 8,
  },
  getStartedButtonText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "600",
  },

  // Download Screen Styles
  downloadCard: {
    alignItems: "center",
    padding: 20,
    margin: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  downloadTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: "#000000",
    marginTop: 20,
    marginBottom: 10,
    textAlign: "center",
  },
  downloadSubtitle: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
    marginBottom: 30,
  },
  progressContainer: {
    width: "100%",
    alignItems: "center",
  },
  progressText: {
    fontSize: 16,
    color: "#007AFF",
    marginTop: 10,
  },
  settingsButton: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  modelList: {
    marginTop: 20,
    width: "100%",
  },
  modelButtonText: {
    color: "#1E40AF",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
  },
});
